# attacker_ue — srsue #2 (ZMQ) · rogue SIM. enb2와 1:1 ZMQ(2101/2100). USIM=가입자 001010000000002.
[rf]
device_name = zmq
device_args = tx_port=tcp://*:2101,rx_port=tcp://ran_enb2:2100,id=ue2,base_srate=23.04e6

[rat.eutra]
dl_earfcn    = 3350
nof_carriers = 1

[usim]
mode = soft
algo = milenage
opc  = e8ed289deba952e4283b54e88e6183ca
k    = 000102030405060708090a0b0c0d0e0f
imsi = 001010000000002
imei = 353490069873320

[rrc]
[nas]
apn = internet

[gw]

[gui]
enable = false

[log]
all_level     = warning
filename      = /tmp/ue2.log
file_max_size = 51200
